# This workflow will build the TourGuide .NET project.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net.

name: Build, test and deploy ASP.NET Core TourGuide API App

# specifies GitHub events that triggers the workflow
on:
  push:
    branches: [ "master", "Dev" ]
  pull_request:
    branches: [ "master", "Dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # GitHub project repository checkout for allowing workflow to access it.
    - uses: actions/checkout@v4    
    # (upd) Set a .NET CLI environment and defines .NET version to use (7.0 used by TourGuide App).
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x        
    # Check external dependencies in project files and use NuGet for downloading them (Swashbuckle / OpenApi).
    - name: Restore dependencies
      run: dotnet restore
    # Generates a project and all of its dependencies.
    - name: Build
      run: dotnet build --no-restore
    # .NET test driver used to execute unit tests.
    - name: Unit tests
      run: dotnet test --no-build --verbosity normal
    - run: |
        mkdir -p ${{ github.workspace }}/publish
    # (add) Publishes App and its dependencies in Publish dir for deployment using release configuraton for hosting system.
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
    # (add) Zip file in Publish dir.
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TourGuide-${{ github.sha }}
        path: ${{ github.workspace }}/publish
